import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Innstillinger",
  type: "document",
  groups: [
    { name: "availability", title: "Tilgjengelighet", default: true },
    { name: "prices", title: "Priser" },
    { name: "contact", title: "Kontakt" },
  ],
  fields: [
    defineField({
      name: "isAvailable",
      title: "Tilgjengelig for oppdrag",
      description: "Av = offshore.",
      type: "boolean",
      initialValue: true,
      group: "availability",
    }),
    defineField({
      name: "availableText",
      title: "Tekst når jeg er i land",
      description: "Vises på forsiden og kontaktsiden når «Tilgjengelig» er på.",
      type: "text",
      rows: 3,
      group: "availability",
    }),
    defineField({
      name: "offshoreText",
      title: "Tekst når jeg er offshore",
      description: "Vises på forsiden og kontaktsiden når «Tilgjengelig» er av.",
      type: "text",
      rows: 3,
      group: "availability",
    }),
    defineField({
      name: "installPrice",
      title: "Pris montering (kr)",
      type: "number",
      validation: (rule) => rule.min(0),
      group: "prices",
    }),
    defineField({
      name: "servicePrice",
      title: "Pris service (kr)",
      type: "number",
      validation: (rule) => rule.min(0),
      group: "prices",
    }),
    defineField({
      name: "serviceDiscountPercent",
      title: "Rabatt serviceavtale (%)",
      type: "number",
      validation: (rule) => rule.min(0).max(100),
      group: "prices",
    }),
    defineField({ name: "phone", title: "Telefon", type: "string", group: "contact" }),
    defineField({ name: "email", title: "E-post", type: "string", group: "contact" }),
    defineField({ name: "address", title: "Adresse", type: "string", group: "contact" }),
    defineField({ name: "orgNr", title: "Org.nr.", type: "string", group: "contact" }),
    defineField({
      name: "footerTagline",
      title: "Kort beskrivelse i bunnteksten",
      type: "text",
      rows: 2,
      group: "contact",
    }),
  ],
  preview: { prepare: () => ({ title: "Innstillinger" }) },
});
